<a href="https://colab.research.google.com/github/mingma1369/Python/blob/main/Lecture23_Missing_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
data=Series(['one','two',np.nan,'four'])
data

0     one
1     two
2     NaN
3    four
dtype: object

In [3]:
data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
data.dropna()

0     one
1     two
3    four
dtype: object

In [6]:
dframe = DataFrame([[1,2,3],[np.nan,5,6],[7,np.nan,9],[np.nan,np.nan,np.nan]])
dframe

     0    1    2
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  7.0  NaN  9.0
3  NaN  NaN  NaN

In [7]:
clean_dframe=dframe.dropna()
clean_dframe

     0    1    2
0  1.0  2.0  3.0

In [8]:
dframe.dropna(how='all')

     0    1    2
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  7.0  NaN  9.0

In [9]:
dframe.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [11]:
npn=np.nan
dframe2 = DataFrame([[1,2,3,npn],[2,npn,5,6],[npn,7,npn,9],[1,npn,npn,npn]])
dframe2

     0    1    2    3
0  1.0  2.0  3.0  NaN
1  2.0  NaN  5.0  6.0
2  NaN  7.0  NaN  9.0
3  1.0  NaN  NaN  NaN

In [12]:
dframe2.dropna(thresh=2) #at least two numbers in the row

     0    1    2    3
0  1.0  2.0  3.0  NaN
1  2.0  NaN  5.0  6.0
2  NaN  7.0  NaN  9.0

In [13]:
dframe2.dropna(thresh=3)

     0    1    2    3
0  1.0  2.0  3.0  NaN
1  2.0  NaN  5.0  6.0

In [14]:
dframe2

     0    1    2    3
0  1.0  2.0  3.0  NaN
1  2.0  NaN  5.0  6.0
2  NaN  7.0  NaN  9.0
3  1.0  NaN  NaN  NaN

In [16]:
dframe2.fillna(1)

     0    1    2    3
0  1.0  2.0  3.0  1.0
1  2.0  1.0  5.0  6.0
2  1.0  7.0  1.0  9.0
3  1.0  1.0  1.0  1.0

In [17]:
dframe2

     0    1    2    3
0  1.0  2.0  3.0  NaN
1  2.0  NaN  5.0  6.0
2  NaN  7.0  NaN  9.0
3  1.0  NaN  NaN  NaN

In [18]:
dframe2.fillna({0:0,1:1,2:2,3:3})

     0    1    2    3
0  1.0  2.0  3.0  3.0
1  2.0  1.0  5.0  6.0
2  0.0  7.0  2.0  9.0
3  1.0  1.0  2.0  3.0

In [19]:
dframe2.fillna(0)

     0    1    2    3
0  1.0  2.0  3.0  0.0
1  2.0  0.0  5.0  6.0
2  0.0  7.0  0.0  9.0
3  1.0  0.0  0.0  0.0

In [20]:
dframe2

     0    1    2    3
0  1.0  2.0  3.0  NaN
1  2.0  NaN  5.0  6.0
2  NaN  7.0  NaN  9.0
3  1.0  NaN  NaN  NaN

In [21]:
dframe2.fillna(0,inplace=True)
dframe2

     0    1    2    3
0  1.0  2.0  3.0  0.0
1  2.0  0.0  5.0  6.0
2  0.0  7.0  0.0  9.0
3  1.0  0.0  0.0  0.0